# _config.yml
title: ろうそく
description: ぶろぐさいと！
baseurl: "/blog"
url: "https://asiraat.github.io"

# Excerpt settings
excerpt_separator: <!--more-->
excerpt_length: 150

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
# Custom collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# _layouts/default.html
# _layouts/post.html
#消して別フォルダに移行

# assets/css/main.scss
