baseURL = "https://Asiraat.github.io/"
languageCode = "ja-jp"
title = "My Blog"
theme = "ananke"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog-list/"
    weight = 2

[params]
  favicon = ""
  site_logo = ""
  description = "A simple blog created with Hugo and GitHub Pages"
  facebook = ""
  twitter = "https://twitter.com/yourusername"
  instagram = ""
  youtube = ""
  github = "https://github.com/yourusername"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
