# _config.yml
title: ろうそく
description: ぶろぐさいと！
baseurl: "/blog"
url: "https://asiraat.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
# Custom collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% if page.title %}{{ page.title }} - {% endif %}{{ site.title }}</title>
    <link rel="stylesheet" href="{{ '/assets/css/blog.css' | relative_url }}">
    <link rel="icon" href="{{ '/assets/images/favicon.ico' | relative_url }}">
</head>
<body>
    <div class="top-bar">
     <p class="top-bar-text">
       <a href="{{ '/' | relative_url }}" class="custom-link">{{ site.title }}</a>
     </p>
    </div>
    
    <div class="content">
        {{ content }}
    </div>
    
    <footer>
        <p>&copy; {{ site.time | date: '%Y' }} {{ site.title }}</p>
    </footer>
</body>
</html>

# _layouts/post.html
---
layout: default
---
<article class="post">
    <h1>{{ page.title }}</h1>
    <p class="post-meta">{{ page.date | date: "%Y-%m-%d" }}</p>
    {{ content }}
    {% if page.tags %}
    <p class="post-tags">
        Tags: {{ page.tags | join: ", " }}
    </p>
    {% endif %}
</article>


# assets/css/main.scss
---
---
@import "minima";

body {
    font-family: 'Helvetica Neue', Arial, sans-serif;
    line-height: 1.6;
    color: #333;
}

header {
    background-color: #f8f8f8;
    padding: 1rem 0;
    text-align: center;
}

header img {
    max-width: 100%;
    height: auto;
}

main {
    max-width: 800px;
    margin: 0 auto;
    padding: 2rem 1rem;
}

.post-meta {
    color: #666;
    font-size: 0.9rem;
}

.post-tags {
    font-style: italic;
}
